[paths]
app_path = "Maestral/app"
app_packages_path = "Maestral/app_packages"
support_path = "Support"

icon.16 = "Maestral/Assets.xcassets/Maestral.appiconset/icon-16.png"
icon.32 = "Maestral/Assets.xcassets/Maestral.appiconset/icon-32.png"
icon.64 = "Maestral/Assets.xcassets/Maestral.appiconset/icon-64.png"
icon.128 = "Maestral/Assets.xcassets/Maestral.appiconset/icon-128.png"
icon.256 = "Maestral/Assets.xcassets/Maestral.appiconset/icon-256.png"
icon.512 = "Maestral/Assets.xcassets/Maestral.appiconset/icon-512.png"
icon.1024 = "Maestral/Assets.xcassets/Maestral.appiconset/icon-1024.png"
